### ISSUE TITLE
patches won´t apply

### ISSUE THREAD

**Issue by TinoKossmann** [user987654321resu/Libre2-patched-App#1]
Any ideas why the patches aren't being applied?

kossmann@nuc:/usr/src/$ **uname -a**
Linux nuc 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

kossmann@nuc:/usr/src$ **git clone https://github.com/user987654321resu/Libre2-patched-App**
Klone nach 'Libre2-patched-App' ...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 1), reused 10 (delta 1), pack-reused 0
Entpacke Objekte: 100% (10/10), Fertig.

kossmann@nuc:/usr/src/Libre2-patched-App$ **md5sum /tmp/com.freestylelibre.app.de_2019-04-22.apk xdrip2.git.patch**
420735605bacf0e18d2570079ebaa238   com.freestylelibre.app.de_2019-04-22.apk
2242126779112c1f71d0ba325af72e86   xdrip2.git.patch

kossmann@nuc:/usr/src/Libre2-patched-App$ **apktool d -o librelink /tmp/com.freestylelibre.app.de_2019-04-22.apk**
I: Using Apktool 2.3.4-dirty on com.freestylelibre.app.de_2019-04-22.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/kossmann/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

kossmann@nuc:/usr/src/Libre2-patched-App/librelink$ **md5sum AndroidManifest.xml**
400cf966e8bd324f10fd2ee7e360bc35  AndroidManifest.xml

kossmann@nuc:/usr/src/Libre2-patched-App/librelink$ **git apply -v ../xdrip2.git.patch**
Patch 'AndroidManifest.xml' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/components/DaggerAppComponent.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/modules/AppModule$2.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/ui/common/ScanSensorActivity.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/ui/help/EventLogActivity.smali' ausgelassen.
Patch 'res/menu/navdrawer.xml' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/BleManager$5.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/FirebaseTree.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/types/ApplicationConfigurationValues.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/BleManager.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/App.smali' ausgelassen.
Patch 'res/menu/default_menu.xml' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/PatchEventFirebaseUploader.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/App_MembersInjector.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/BleManager$3.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/modules/AppModule.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/ui/common/ScanSensorFragment.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/BleManager$3$2.smali' ausgelassen.
Patch 'res/layout/eventlog_activity.xml' ausgelassen.
Patch 'smali_classes2/com/librelink/app/core/modules/AppModule$2$1.smali' ausgelassen.
Patch 'smali_classes2/com/librelink/app/ui/help/HelpActivity.smali' ausgelassen.

**Comment by user987654321resu** [comment]
Please try to apply the patch to the librelink folder outside of the patch repository

**Comment by TinoKossmann** [comment]
looks better :-) whitespace warnings could be ignored?

kossmann@nuc:/tmp/librelink$ **git apply -v /usr/src/Libre2-patched-App/xdrip2.git.patch**
/usr/src/Libre2-patched-App/xdrip2.git.patch:626: trailing whitespace.

/usr/src/Libre2-patched-App/xdrip2.git.patch:1084: trailing whitespace.

/usr/src/Libre2-patched-App/xdrip2.git.patch:1092: trailing whitespace.

/usr/src/Libre2-patched-App/xdrip2.git.patch:1094: trailing whitespace.

/usr/src/Libre2-patched-App/xdrip2.git.patch:1180: trailing whitespace.

Prüfe Patch AndroidManifest.xml ...
Prüfe Patch smali_classes2/com/librelink/app/core/components/DaggerAppComponent.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/modules/AppModule$2.smali ...
Prüfe Patch smali_classes2/com/librelink/app/ui/common/ScanSensorActivity.smali ...
Prüfe Patch smali_classes2/com/librelink/app/ui/help/EventLogActivity.smali ...
Prüfe Patch res/menu/navdrawer.xml ...
Prüfe Patch smali_classes2/com/librelink/app/core/BleManager$5.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/FirebaseTree.smali ...
Prüfe Patch smali_classes2/com/librelink/app/types/ApplicationConfigurationValues.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/BleManager.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/App.smali ...
Prüfe Patch res/menu/default_menu.xml ...
Prüfe Patch smali_classes2/com/librelink/app/core/PatchEventFirebaseUploader.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/App_MembersInjector.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/BleManager$3.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/modules/AppModule.smali ...
Prüfe Patch smali_classes2/com/librelink/app/ui/common/ScanSensorFragment.smali ...
Prüfe Patch smali_classes2/com/librelink/app/core/BleManager$3$2.smali ...
Prüfe Patch res/layout/eventlog_activity.xml ...
Prüfe Patch smali_classes2/com/librelink/app/core/modules/AppModule$2$1.smali ...
Prüfe Patch smali_classes2/com/librelink/app/ui/help/HelpActivity.smali ...
Patch AndroidManifest.xml sauber angewendet
Patch smali_classes2/com/librelink/app/core/components/DaggerAppComponent.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/modules/AppModule$2.smali sauber angewendet
Patch smali_classes2/com/librelink/app/ui/common/ScanSensorActivity.smali sauber angewendet
Patch smali_classes2/com/librelink/app/ui/help/EventLogActivity.smali sauber angewendet
Patch res/menu/navdrawer.xml sauber angewendet
Patch smali_classes2/com/librelink/app/core/BleManager$5.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/FirebaseTree.smali sauber angewendet
Patch smali_classes2/com/librelink/app/types/ApplicationConfigurationValues.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/BleManager.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/App.smali sauber angewendet
Patch res/menu/default_menu.xml sauber angewendet
Patch smali_classes2/com/librelink/app/core/PatchEventFirebaseUploader.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/App_MembersInjector.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/BleManager$3.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/modules/AppModule.smali sauber angewendet
Patch smali_classes2/com/librelink/app/ui/common/ScanSensorFragment.smali sauber angewendet
Patch smali_classes2/com/librelink/app/core/BleManager$3$2.smali sauber angewendet
Patch res/layout/eventlog_activity.xml sauber angewendet
Patch smali_classes2/com/librelink/app/core/modules/AppModule$2$1.smali sauber angewendet
Patch smali_classes2/com/librelink/app/ui/help/HelpActivity.smali sauber angewendet
warning: 5 Zeilen fügen Whitespace-Fehler hinzu.

**Comment by user987654321resu** [comment]
Looks good. Some whitespace fuu is always happening

**Comment by Pipsko** [comment]
I am having a bit of a trouble myself. The patch does not apply properly using "Git Bash".
### 
**Starting in CMD**
C:\Users\phili\Desktop\Loop\Patch Libre\Master>apktool d -o librelink "C:\Users\phili\Desktop\Loop\Patch Libre\Master\org Libre Apk\com.freestylelibre.app.de_2019-04-22.apk"
I: Using Apktool 2.3.4 on com.freestylelibre.app.de_2019-04-22.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\phili\AppData\Local\apktool\framework), using C:\Users\phili\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\phili\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

**So far so good.**
**Continuing_ with Git (Bash)**

phili@Zion MINGW64 ~/Desktop/Loop/Patch Libre/Patch1/librelink
$ git apply '/c/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch'
C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:626: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1084: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1092: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1094: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1180: trailing whitespace.

error: patch failed: AndroidManifest.xml:3
error: AndroidManifest.xml: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/components/DaggerAppComponent.smali:1169
error: smali_classes2/com/librelink/app/core/components/DaggerAppComponent.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/modules/AppModule$2.smali:20
error: smali_classes2/com/librelink/app/core/modules/AppModule$2.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/ui/common/ScanSensorActivity.smali:98
error: smali_classes2/com/librelink/app/ui/common/ScanSensorActivity.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/ui/help/EventLogActivity.smali:321
error: smali_classes2/com/librelink/app/ui/help/EventLogActivity.smali: patch does not apply
error: patch failed: res/menu/navdrawer.xml:22
error: res/menu/navdrawer.xml: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/BleManager$5.smali:187
error: smali_classes2/com/librelink/app/core/BleManager$5.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/FirebaseTree.smali:44
error: smali_classes2/com/librelink/app/core/FirebaseTree.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/types/ApplicationConfigurationValues.smali:33
error: smali_classes2/com/librelink/app/types/ApplicationConfigurationValues.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/BleManager.smali:354
error: smali_classes2/com/librelink/app/core/BleManager.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/App.smali:18
error: smali_classes2/com/librelink/app/core/App.smali: patch does not apply
error: patch failed: res/menu/default_menu.xml:2
error: res/menu/default_menu.xml: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/PatchEventFirebaseUploader.smali:26
error: smali_classes2/com/librelink/app/core/PatchEventFirebaseUploader.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/App_MembersInjector.smali:38
error: smali_classes2/com/librelink/app/core/App_MembersInjector.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/BleManager$3.smali:183
error: smali_classes2/com/librelink/app/core/BleManager$3.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/modules/AppModule.smali:1821
error: smali_classes2/com/librelink/app/core/modules/AppModule.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/ui/common/ScanSensorFragment.smali:172
error: smali_classes2/com/librelink/app/ui/common/ScanSensorFragment.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/BleManager$3$2.smali:116
error: smali_classes2/com/librelink/app/core/BleManager$3$2.smali: patch does not apply
error: patch failed: res/layout/eventlog_activity.xml:4
error: res/layout/eventlog_activity.xml: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/core/modules/AppModule$2$1.smali:49
error: smali_classes2/com/librelink/app/core/modules/AppModule$2$1.smali: patch does not apply
error: patch failed: smali_classes2/com/librelink/app/ui/help/HelpActivity.smali:186
error: smali_classes2/com/librelink/app/ui/help/HelpActivity.smali: patch does not apply

**My System**
phili@Zion MINGW64 ~/Desktop/Loop/Patch Libre/Patch1/librelink
$ uname -a
MINGW64_NT-10.0-17763 Zion 3.0.7-338.x86_64 2019-04-30 21:52 UTC x86_64 Msys

**checksum**
phili@Zion MINGW64 ~/Desktop/Loop/Patch Libre/Patch1/librelink
$ md5sum '/c/Users/phili/Desktop/Loop/Patch Libre/Master/org Libre Apk/com.freestylelibre.app.de_2019-04-22.apk'
420735605bacf0e18d2570079ebaa238 */c/Users/phili/Desktop/Loop/Patch Libre/Master/org Libre Apk/com.freestylelibre.app.de_2019-04-22.apk

phili@Zion MINGW64 ~/Desktop/Loop/Patch Libre/Patch1/librelink
$ md5sum '/c/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch'
2242126779112c1f71d0ba325af72e86 */c/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch


_That is my outcome. Same text/occurence in CMD. At this moment I do not know how to proceed.
A little help is very much appreciated. I got 10 days left on my current sensor. 
I hope I can use the patched app with the next sensor._

**Cudos for the patched Libe2 App!**

**Comment by MasterPlexus** [comment]
The Patchfiles must be beside the decompiled LibreLink folder, not in a other place.just copy them.in the same folder where the LibreLink folder is stored.

**Comment by Pipsko** [comment]
> The Patchfiles must be beside the decompiled LibreLink folder, not in a other place.just copy them.in the same folder where the LibreLink folder is stored.

Thanks for the help. Unfortunately I don´t quite get it. I have saved the librelink folder, source folder, xdrip2.git.patch and xdrip2.patch in the same folder (e.g. Patch1).

phili@Zion MINGW64 ~/Desktop/Loop/Patch Libre/**Patch1**/librelink
$ git apply '/c/Users/phili/Desktop/Loop/Patch Libre/**Patch1**/xdrip2.git.patch'

![Patch Folder exmpl](https://user-images.githubusercontent.com/45955102/61629261-a8d98900-ac84-11e9-82cc-fe935bc54a16.JPG)

Am I missing s. th.? Maybe I am missing the forest through the trees?

**Comment by TinoKossmann** [comment]
No, the "librelink" directory has to be outside the GIT-directory, e.g. beside it or somewhere else.

For example:
C:\Users\phili\Desktop\Loop\Patch Libre\Patch1\ - with GIT stuff inside (xdrip2.git.patch, sources, ...)
C:\Users\phili\Desktop\Loop\librelink - with apktool stuff inside

**Comment by serejks** [comment]
Hey, @user987654321resu 
Can you, please, share patched apk?
In pm, please!
Thanks!

**Comment by Pipsko** [comment]
> No, the "librelink" directory has to be outside the GIT-directory, e.g. beside it or somewhere else.
> 
> For example:
> C:\Users\phili\Desktop\Loop\Patch Libre\Patch1\ - with GIT stuff inside (xdrip2.git.patch, sources, ...)
> C:\Users\phili\Desktop\Loop\librelink - with apktool stuff inside

phili@Zion MINGW64 ~/Desktop/Loop/librelink
$ git apply '/c/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch'
C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:626: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1084: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1092: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1094: trailing whitespace.

C:/Users/phili/Desktop/Loop/Patch Libre/Patch1/xdrip2.git.patch:1180: trailing whitespace.

warning: 5 lines add whitespace errors.

_Is this it?_

**Comment by TinoKossmann** [comment]
Yes, looks good.

**Comment by Pipsko** [comment]
Thanks a lot. I was a bit unsure because your resulting post was a bit longer in text...e.g. "Prüfe patch..."
I just got the above posted text and nothing else.
