### ISSUE TITLE
Provide interface for calculating BG from raw data from xDrip using Libre 2 as CGM 

### ISSUE THREAD

**Issue by Paulusma** [user987654321resu/Libre2-patched-App#17]
Currently miaomiao allows Libre1 to be used as CGM for xDrip, OOP algorithm is used to calculate BG from raw sensor data.

Would be nice if patched app supports this for Libre2 once miaomiao for Libre2 is out!

**Comment by MasterPlexus** [comment]
not clear if I understand. The patched app provides data wich are still error corrected, and also Tempratur corrected. I see no point why the OOP is needed for that approach...

**Comment by jroth-haj** [comment]
LibreOOPAlgorithm was updated. Now you can NFC scan and get Abbott calculated data in xDrip. The patched App ist for direct recieving BG without transmitter Like Miaomiao.

**Comment by Paulusma** [comment]
OK thx for the replies,
